"use client";

/* ------------------------------------------------------------------ */
/* Icon library for the CRM's icon picker.                             */
/*                                                                     */
/* Lucide ships thousands of glyphs; importing all of them would pull   */
/* the entire set into the client bundle for the sake of one badge on   */
/* a category card. This is the curated travel-shop subset — grouped    */
/* the way an editor looks for one, and named so the stored value stays */
/* readable in localStorage ("TreePalm", not an index).                 */
/* ------------------------------------------------------------------ */

import {
  Accessibility,
  Activity,
  AirVent,
  Anchor,
  Apple,
  Award,
  Baby,
  Backpack,
  BadgeCheck,
  BadgeIndianRupee,
  BadgePercent,
  Banana,
  Bath,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Bike,
  Binoculars,
  Bird,
  Book,
  BookOpen,
  Boxes,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  CalendarRange,
  Camera,
  Candy,
  Car,
  CarFront,
  Caravan,
  Carrot,
  Castle,
  Check,
  CheckCheck,
  Cherry,
  Church,
  Cigarette,
  CircleHelp,
  ClipboardList,
  Clock,
  CloudLightning,
  CloudRain,
  CloudSun,
  Coffee,
  Compass,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Dog,
  Donut,
  DoorOpen,
  Drama,
  Droplet,
  Droplets,
  Drum,
  Dumbbell,
  Earth,
  Egg,
  FileText,
  Film,
  Filter,
  Fish,
  Flag,
  FlagTriangleRight,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  Grape,
  Guitar,
  Ham,
  Hammer,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hotel,
  IceCreamCone,
  Image,
  IndianRupee,
  Info,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Languages,
  Layers,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Luggage,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Martini,
  MessageCircle,
  Mic,
  Microwave,
  Milestone,
  Milk,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Newspaper,
  Orbit,
  Package,
  PackageCheck,
  Palette,
  ParkingCircle,
  PartyPopper,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plug,
  Popcorn,
  Puzzle,
  QrCode,
  Radio,
  Refrigerator,
  Rocket,
  Route,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scan,
  ScrollText,
  Search,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Signpost,
  SignpostBig,
  SlidersHorizontal,
  Smile,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Stars,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Tag,
  Tags,
  Telescope,
  Tent,
  TentTree,
  Theater,
  Thermometer,
  ThumbsUp,
  Ticket,
  TicketPercent,
  Timer,
  TrainFront,
  TrainTrack,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Wand,
  Warehouse,
  WashingMachine,
  Waves,
  Waypoints,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { createElement } from "react";

export const ICON_LIBRARY: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  AirVent,
  Anchor,
  Apple,
  Award,
  Baby,
  Backpack,
  BadgeCheck,
  BadgeIndianRupee,
  BadgePercent,
  Banana,
  Bath,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Bike,
  Binoculars,
  Bird,
  Book,
  BookOpen,
  Boxes,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  CalendarRange,
  Camera,
  Candy,
  Car,
  CarFront,
  Caravan,
  Carrot,
  Castle,
  Check,
  CheckCheck,
  Cherry,
  Church,
  Cigarette,
  CircleHelp,
  ClipboardList,
  Clock,
  CloudLightning,
  CloudRain,
  CloudSun,
  Coffee,
  Compass,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Dog,
  Donut,
  DoorOpen,
  Drama,
  Droplet,
  Droplets,
  Drum,
  Dumbbell,
  Earth,
  Egg,
  FileText,
  Film,
  Filter,
  Fish,
  Flag,
  FlagTriangleRight,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  Grape,
  Guitar,
  Ham,
  Hammer,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hotel,
  IceCreamCone,
  Image,
  IndianRupee,
  Info,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Languages,
  Layers,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Luggage,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Martini,
  MessageCircle,
  Mic,
  Microwave,
  Milestone,
  Milk,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Newspaper,
  Orbit,
  Package,
  PackageCheck,
  Palette,
  ParkingCircle,
  PartyPopper,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plug,
  Popcorn,
  Puzzle,
  QrCode,
  Radio,
  Refrigerator,
  Rocket,
  Route,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scan,
  ScrollText,
  Search,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Signpost,
  SignpostBig,
  SlidersHorizontal,
  Smile,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Stars,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Tag,
  Tags,
  Telescope,
  Tent,
  TentTree,
  Theater,
  Thermometer,
  ThumbsUp,
  Ticket,
  TicketPercent,
  Timer,
  TrainFront,
  TrainTrack,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Wand,
  Warehouse,
  WashingMachine,
  Waves,
  Waypoints,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
};

export type IconName = keyof typeof ICON_LIBRARY;

export const ICON_GROUPS: { title: string; icons: string[] }[] = [
  {
    title: "Travel & transport",
    icons: ["Plane", "PlaneTakeoff", "PlaneLanding", "TrainFront", "TrainTrack", "Bus", "Car", "CarFront", "Caravan", "Ship", "Sailboat", "Anchor", "Bike", "Rocket", "Fuel", "ParkingCircle", "Luggage", "Briefcase", "BriefcaseBusiness", "Backpack", "Ticket", "TicketPercent", "Route", "Waypoints", "Footprints", "Milestone", "Signpost", "SignpostBig", "Navigation", "Compass", "Map", "MapPin", "MapPinned", "Globe", "Earth", "LifeBuoy", "Satellite"],
  },
  {
    title: "Nature & outdoors",
    icons: ["Mountain", "MountainSnow", "TreePalm", "TreePine", "Trees", "Waves", "Sun", "Sunrise", "Sunset", "CloudSun", "CloudRain", "CloudLightning", "Snowflake", "Wind", "Droplet", "Droplets", "Thermometer", "Moon", "MoonStar", "Stars", "Umbrella", "Tent", "TentTree", "Flower", "Flower2", "Leaf", "Sprout", "Wheat", "Bird", "Fish", "Dog", "Snail", "Binoculars", "Telescope"],
  },
  {
    title: "Stays & places",
    icons: ["Hotel", "BedDouble", "BedSingle", "DoorOpen", "Key", "KeyRound", "Building", "Building2", "Warehouse", "Store", "Landmark", "Castle", "Church", "Sofa", "Tv", "AirVent", "ShowerHead", "Bath", "WashingMachine", "Refrigerator", "Microwave", "Wifi", "Plug", "Lamp", "Flashlight"],
  },
  {
    title: "Food & drink",
    icons: ["Utensils", "UtensilsCrossed", "CookingPot", "Coffee", "CupSoda", "Wine", "Beer", "Martini", "Milk", "IceCreamCone", "Pizza", "Soup", "Salad", "Sandwich", "Croissant", "Cookie", "Donut", "Popcorn", "Candy", "Cake", "Apple", "Cherry", "Grape", "Banana", "Carrot", "Egg", "Beef", "Ham"],
  },
  {
    title: "People & occasions",
    icons: ["Users", "UsersRound", "UserRound", "UserCheck", "Baby", "PersonStanding", "Heart", "HeartHandshake", "HeartPulse", "PartyPopper", "Gift", "Smile", "ThumbsUp", "Accessibility", "Languages", "Drama", "Theater", "Music", "Guitar", "Drum", "Mic", "Radio", "Gamepad2", "Puzzle", "Volleyball", "Dumbbell", "Camera", "Film", "Image", "Palette", "Brush"],
  },
  {
    title: "Value & trust",
    icons: ["Star", "Sparkle", "Sparkles", "Gem", "Crown", "Award", "Trophy", "BadgeCheck", "ShieldCheck", "Shield", "Check", "CheckCheck", "Wallet", "CreditCard", "IndianRupee", "BadgeIndianRupee", "PiggyBank", "Tag", "Tags", "Percent", "BadgePercent", "TrendingUp", "Zap", "Flame", "Activity", "Lightbulb"],
  },
  {
    title: "Interface & admin",
    icons: ["CalendarDays", "CalendarCheck", "CalendarHeart", "CalendarRange", "Clock", "Timer", "Search", "Filter", "SlidersHorizontal", "Settings", "Wrench", "Hammer", "LayoutGrid", "Layers", "Boxes", "Package", "PackageCheck", "ShoppingBag", "ShoppingCart", "ListChecks", "ClipboardList", "FileText", "ScrollText", "BookOpen", "Book", "Newspaper", "Info", "CircleHelp", "Phone", "PhoneCall", "MessageCircle", "Mail", "Headset", "Flag", "FlagTriangleRight", "Scan", "QrCode", "Orbit", "Shapes", "Wand", "Sword", "Swords", "Stethoscope", "Pill", "Cross", "Syringe", "Glasses", "Cigarette"],
  },
];

/** Splits "TreePalm" into "Tree Palm" so the picker's search box matches the
    way an editor would type it. */
export const humanizeIconName = (name: string) =>
  name.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/([A-Za-z])(\d)/g, "$1 $2");

/** Never throws on a stored name that has since left the library. */
export function getIcon(name: string): LucideIcon {
  return ICON_LIBRARY[name] ?? ICON_LIBRARY.MapPin;
}

/** Renders an icon by its stored name.

    Looking a component up by name means assigning it to a capitalised const,
    which inside a render body reads as "component created during render" —
    so the lookup is done once, here, through createElement. */
export function Glyph({
  name,
  className = "size-5",
  strokeWidth = 2,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  return createElement(getIcon(name), {
    className,
    strokeWidth,
    "aria-hidden": "true",
  });
}
