// Generated by `npm run build:cloudflare` before Wrangler bundles this entry.
import './.open-next/server-functions/default/handler.mjs';
import handler from './.open-next/worker.js';
export { DOQueueHandler } from './.open-next/worker.js';

const worker = {
  fetch: handler.fetch,
  async scheduled(_event, env, ctx) {
    if (!env.CRON_SECRET) throw new Error('CRON_SECRET is required for quote cleanup.');
    const request = new Request('https://comparemytrip.internal/api/cron/quote-cleanup', {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    // Use the same application handler as HTTP requests, including its env
    // context. Never send the secret to an externally supplied URL.
    const response = await handler.fetch(request, env, ctx);
    await response.arrayBuffer();
    if (!response.ok) throw new Error(`Quote cleanup failed with HTTP ${response.status}.`);
  },
};

export default worker;
