import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, Check, ChevronDown, MousePointer2 } from "lucide-react";
import { ADMIN_NAV_GROUPS } from "../_components/adminNavigation";

export const metadata: Metadata = { title: "How to use admin", description: "A simple guide to managing CompareMyTrip." };

const TASKS = [
  { title: "Respond to a new customer request", href: "/admin/enquiries", link: "Open contact enquiries", steps: ["Choose the right inbox: Contact enquiries for general questions, Package quotes for customised prices, or Trip planning leads for visitors who need planning help.", "Use the status filters to find new requests. Open a request to see the traveller’s full details.", "Use the email or phone link to contact the traveller. Update the status after you follow up; status changes save automatically."] },
  { title: "Confirm a booking and set its departure", href: "/admin/trips", link: "Open bookings & payments", steps: ["Find the traveller or booking reference. Check the payment status and any payment warnings first.", "Review the package and traveller details, then choose the appropriate booking status. Payment status and booking status are shown separately.", "Enter the confirmed departure date. Use the field’s save control where shown. If a payment is disputed, review its payment report before taking further action."] },
  { title: "Create or update a travel package", href: "/admin/packages", link: "Open travel packages", steps: ["Choose Create package, or find an existing package and select Edit. If this is the first setup, initialise the catalogue using the setup prompt.", "Click the text directly in the package preview to edit it. Click outside to apply, or press Escape to cancel. Add photos, itinerary days and content in place. Use Undo to restore the previous edit, and open Catalogue & booking settings for categories and departure weekdays.", "Use View as traveller to check the page. Choose Draft or Published in the top bar, then Save package. AI import is available above the preview if you want to start from a PDF."] },
  { title: "Change text, photos or sections on the website", href: "/admin/content", link: "Open pages & content", steps: ["Search for the section you want, or choose it from Homepage, Other pages or Across the website.", "Edit the text and images. The visibility switch controls whether that section appears. You can edit several sections before publishing.", "Review the list of changed sections, then publish. Publishing applies all pending changes in this editor to the website. Preview the website in a new tab to check the result."] },
  { title: "Replace a page banner", href: "/admin/banners", link: "Open page banners", steps: ["Choose the page from the page selector. Its current banner appears in the preview.", "Update the heading and photo, and use the preview to check the result. Different pages can have different banner styles.", "Publish when ready. The restore-original option is in the advanced section and replaces that banner’s draft before you publish."] },
  { title: "Offer a discount", href: "/admin/coupons", link: "Open discount codes", steps: ["Create a discount code and enter the discount type and amount.", "Set any minimum spend, start and end dates, usage limits and eligible packages. Check each condition before saving.", "Save the code and check its status in the list. Turn it off when you no longer want customers to use it."] },
  { title: "Write a blog article or travel guide", href: "/admin/blog", link: "Open blog & travel guides", steps: ["Create an article or edit an existing one. Start with its title and summary.", "Add the cover photo and article content using the numbered editor sections. Preview it before publishing.", "Save as a draft for more work later, or publish when it is ready for readers."] },
  { title: "Manage destination photos and your audience", href: "/admin/destinations", link: "Open destinations", steps: ["Destinations come from your travel packages. Edit their cover images in Destinations; the page explains when image changes save automatically.", "Use Customers to find registered travellers and their contact information.", "Use Newsletter subscribers to search newsletter sign-ups or export the list. A subscriber record is separate from a registered customer account."] },
  { title: "Open the website or show the coming-soon page", href: "/admin/content?section=comingSoon", link: "Open website availability", steps: ["Open Pages & content and choose Website availability under Across the website.", "Enable coming-soon mode to show visitors the launch page, or disable it to make the regular website available.", "Publish the change. Administrators can still preview the complete website while coming-soon mode is on."] },
];

export default function AdminGuidePage() {
  return <div className="mx-auto max-w-5xl">
    <header><p className="text-xs font-semibold uppercase tracking-widest text-cmt-primary-900">Help & guidance</p><h1 className="mt-2 font-semibold">A simple guide to your workspace.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-cmt-neutral-500">You don’t need to know how the website is built. Choose what you want to do, follow the steps, and use the save message to check your work.</p></header>
    <section className="mt-7 grid gap-5 rounded-2xl border border-cmt-primary-100 bg-cmt-primary-50/70 p-6 sm:grid-cols-3" aria-label="The basics">
      {[{ icon: MousePointer2, title: "1. Choose a work area", text: "The left menu groups related tasks. Search at the top also understands words like payments, photos and coupons." }, { icon: Check, title: "2. Make and save your change", text: "Editors show whether changes are saved, unpublished or saving automatically. Wait for a success message." }, { icon: BookOpen, title: "3. Check the result", text: "Use View website to open a preview in a separate tab. Your admin workspace stays open." }].map(({ icon: Icon, title, text }) => <div key={title}><Icon className="size-5 text-cmt-primary-900" /><h2 className="mt-3 text-sm font-semibold">{title}</h2><p className="mt-2 text-xs leading-6 text-cmt-neutral-600">{text}</p></div>)}
    </section>
    <h2 className="mt-9 text-lg font-semibold">What would you like to do?</h2><p className="mt-1 text-sm text-cmt-neutral-500">Open a task for its step-by-step instructions.</p>
    <div className="mt-4 space-y-3">{TASKS.map((task, index) => <details key={task.title} className="group overflow-hidden rounded-xl border border-cmt-neutral-200 bg-white" open={index === 0}><summary className="flex cursor-pointer list-none items-center gap-3 p-5 text-sm font-semibold [&::-webkit-details-marker]:hidden"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-cmt-neutral-100 text-xs text-cmt-neutral-500">{index + 1}</span><span className="flex-1">{task.title}</span><ChevronDown className="size-4 text-cmt-neutral-400 transition-transform group-open:rotate-180" /></summary><div className="border-t border-cmt-neutral-100 px-5 py-5 sm:pl-16"><ol className="list-decimal space-y-3 pl-4 text-sm leading-7 text-cmt-neutral-600">{task.steps.map((step) => <li key={step} className="pl-1">{step}</li>)}</ol><Link href={task.href} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg bg-cmt-primary-500 px-4 text-xs font-semibold text-cmt-neutral-900 hover:bg-cmt-primary-800">{task.link}<ArrowRight className="size-4" /></Link></div></details>)}</div>
    <section className="mt-8 rounded-2xl border border-cmt-neutral-200 bg-white p-6"><h2 className="text-base font-semibold">Every area, explained</h2><div className="mt-5 grid gap-6 sm:grid-cols-2">{ADMIN_NAV_GROUPS.slice(1).map((group) => <div key={group.label}><h3 className="text-xs font-semibold uppercase tracking-wider text-cmt-neutral-500">{group.label}</h3><ul className="mt-3 space-y-4">{group.items.map((item) => <li key={item.href}><Link href={item.href} className="inline-flex items-center gap-2 text-sm font-semibold text-cmt-primary-900"><item.icon size={15} />{item.label}<ArrowRight size={12} /></Link><p className="mt-1 text-xs leading-5 text-cmt-neutral-500">{item.description}</p></li>)}</ul></div>)}</div></section>
  </div>;
}
