"use client";

import { useRef, useState } from "react";
import { Check, Copy, Download, FileJson, Sparkles, Upload } from "lucide-react";
import { packageAiPrompt } from "@/lib/packageAiPrompt";
import { PACKAGE_IMPORT_MAX_BYTES, parsePackageImport, type ImportedProduct } from "@/lib/packageAiImport";

const button = "inline-flex items-center justify-center gap-2 rounded-cmt-control border px-4 py-2.5 text-sm font-semibold disabled:opacity-50";
const secondaryButton = `${button} border-cmt-neutral-200 bg-white hover:bg-cmt-neutral-50`;

export default function PackageAiImporter({ disabled, onApply }: { disabled: boolean; onApply: (product: ImportedProduct) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const request = useRef(0);
  const [pending, setPending] = useState<ImportedProduct | null>(null);
  const [filename, setFilename] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [reading, setReading] = useState(false);
  const [showPrompt, setShowPrompt] = useState(false);
  const [copied, setCopied] = useState(false);

  async function copyPrompt() {
    try {
      await navigator.clipboard.writeText(packageAiPrompt());
      setCopied(true); setNotice("Prompt copied. Paste it into ChatGPT and attach your PDF or trip information.");
    } catch {
      setCopied(false); setShowPrompt(true); setNotice("Clipboard access is unavailable. Select and copy the prompt below, or download it.");
    }
  }
  function downloadPrompt() {
    const url = URL.createObjectURL(new Blob([packageAiPrompt()], { type: "text/plain;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "comparemytrip-product-prompt.txt";
    document.body.appendChild(link); link.click(); link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  async function readFile(file: File) {
    const token = ++request.current;
    setReading(true); setPending(null); setError(""); setNotice("");
    try {
      if (!file.name.toLowerCase().endsWith(".json")) throw new Error("Upload the .json file generated by ChatGPT. PDFs belong in ChatGPT with the prompt.");
      if (file.size > PACKAGE_IMPORT_MAX_BYTES) throw new Error("Choose a JSON file smaller than 1 MB.");
      const product = parsePackageImport(await file.text());
      if (request.current !== token) return;
      setPending(product); setFilename(file.name);
    } catch (reason) {
      if (request.current === token) setError(reason instanceof Error ? reason.message : "Unable to read this JSON file.");
    } finally {
      if (request.current === token) setReading(false);
    }
  }

  return <section aria-labelledby="package-ai-title" className="mb-8 rounded-cmt-md border border-cmt-primary-100 bg-cmt-primary-50/50 p-5 sm:p-6">
    <div className="flex items-start gap-3">
      <span className="rounded-cmt-control bg-cmt-primary-500 p-2.5"><Sparkles className="size-5" /></span>
      <div><h2 id="package-ai-title" className="font-display text-xl font-semibold">Fill this product with AI</h2><p className="mt-1 text-sm leading-6 text-cmt-neutral-600">Turn your PDF or trip notes into a package. ChatGPT chooses from 1,000 icons and asks about unclear details before creating the JSON.</p></div>
    </div>
    <ol className="my-5 grid list-inside list-decimal gap-3 text-sm text-cmt-neutral-700 sm:grid-cols-3">
      <li>Copy the prompt into ChatGPT and add your PDF or information.</li>
      <li>Answer any questions, then download the JSON from ChatGPT.</li>
      <li>Upload it here, review the details and add your photos.</li>
    </ol>
    <div className="flex flex-wrap gap-2">
      <button type="button" className={`${button} border-cmt-primary-500 bg-cmt-primary-500 hover:bg-cmt-primary-400`} onClick={() => void copyPrompt()}>{copied ? <Check className="size-4" /> : <Copy className="size-4" />}{copied ? "Copy prompt again" : "Copy AI prompt"}</button>
      <button type="button" className={secondaryButton} onClick={downloadPrompt}><Download className="size-4" />Download prompt</button>
      <button type="button" className={secondaryButton} disabled={disabled || reading} onClick={() => input.current?.click()}><Upload className="size-4" />{reading ? "Checking JSON…" : "Upload product JSON"}</button>
      <input ref={input} type="file" accept=".json,application/json" aria-label="Upload product JSON file" className="sr-only" disabled={disabled || reading} onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void readFile(file); }} />
      <button type="button" className="px-3 text-xs font-semibold underline underline-offset-4" aria-expanded={showPrompt} onClick={() => setShowPrompt(value => !value)}>{showPrompt ? "Hide prompt" : "View prompt"}</button>
    </div>
    {showPrompt && <label className="mt-4 block text-sm font-semibold">Prompt to copy<textarea readOnly value={packageAiPrompt()} onFocus={event => event.target.select()} className="mt-2 h-64 w-full rounded-cmt-control border border-cmt-neutral-200 bg-white p-3 font-mono text-xs font-normal" /></label>}
    {notice && <p role="status" className="mt-3 text-sm text-cmt-neutral-700">{notice}</p>}
    {error && <p role="alert" className="mt-4 rounded-cmt-control bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {pending && <div className="mt-5 rounded-cmt-control border border-cmt-neutral-200 bg-white p-4">
      <p className="flex items-center gap-2 text-xs font-semibold text-cmt-neutral-500"><FileJson className="size-4" />Ready to import · {filename}</p>
      <h3 className="mt-2 text-lg font-semibold">{pending.title}</h3>
      <p className="mt-1 text-sm text-cmt-neutral-600">{pending.location} · {pending.nights} nights / {pending.days} days · {pending.dayZeroEnabled ? "Starts at Day 0" : "Starts at Day 1"}</p>
      <p className="mt-2 text-sm">{pending.itinerary.length} itinerary days · {pending.facts.length} quick details · {pending.pageSections.sections.length} extra sections · {pending.price ? `₹${pending.price.toLocaleString("en-IN")} / person` : "Price needs your input"}</p>
      <p className="mt-3 text-sm text-cmt-neutral-600">Applying replaces the product’s text, pricing, itinerary and content sections. Existing photos are kept. Click any text in the preview to adjust it, then save when ready.</p>
      <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={disabled} className={`${button} border-cmt-primary-500 bg-cmt-primary-500 hover:bg-cmt-primary-400`} onClick={() => { onApply(pending); setPending(null); setNotice("Product details filled. Add or check your photos, then review the preview before saving."); }}>Apply to this product</button><button type="button" className={secondaryButton} onClick={() => setPending(null)}>Discard import</button></div>
    </div>}
    <p className="mt-3 text-xs text-cmt-neutral-500">Products only · JSON up to 1 MB · Your file is read in this browser; applying fills the editor without saving.</p>
  </section>;
}
