import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { BENGALURU_COLLECTIONS, BENGALURU_FAQS } from "@/lib/bengaluruCollections";
import { createPageMetadata } from "@/lib/seo";
export const metadata = createPageMetadata({ title: "Trips from Bengaluru | Treks & Holidays", description: "Plan your next trip from Bengaluru. Explore weekend escapes, one-day trips, treks, couple getaways and family holidays, with practical planning guides.", path: "/bengaluru" });
export default function BengaluruPage() {
  return <><Header /><main>
    <section className="bg-cmt-secondary-900 px-5 py-16 text-white sm:py-24"><div className="mx-auto max-w-7xl"><p className="font-semibold text-cmt-primary-400">Bengaluru first. A world of possibilities.</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-semibold sm:text-6xl">Travel experiences for Bengaluru travellers.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">From a sunrise trek to a longer holiday, find a plan that fits your time, budget and travel companions. Start with local departures or ask us to help plan a domestic or international break.</p><Link href="/packages?from=Bengaluru" className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-cmt-primary-500 px-6 font-semibold text-cmt-neutral-900">Explore trips from Bengaluru</Link></div></section>
    <section className="mx-auto max-w-7xl px-5 py-12"><h2 className="font-display text-3xl font-semibold">Choose your kind of break</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{BENGALURU_COLLECTIONS.map(item => <Link key={item.slug} href={`/bengaluru/${item.slug}`} className="rounded-2xl border border-cmt-neutral-200 p-6 transition hover:border-cmt-primary-500 hover:shadow-cmt-sm"><h3 className="font-display text-xl font-semibold">{item.title}</h3><p className="mt-3 leading-7 text-cmt-neutral-600">{item.description}</p><span className="mt-5 block font-semibold">Explore trips & planning guide →</span></Link>)}<Link href="/corporate-group-trips" className="rounded-2xl bg-cmt-primary-100 p-6"><h3 className="font-display text-xl font-semibold">Corporate & group trips</h3><p className="mt-3 leading-7">Planning for colleagues, a college group or friends? Share your requirements for a tailored quote.</p><span className="mt-5 block font-semibold">Plan a group outing →</span></Link></div></section>
    <section className="bg-cmt-neutral-50 px-5 py-12"><div className="mx-auto max-w-7xl"><h2 className="font-display text-3xl font-semibold">Practical guides for your next break</h2><div className="mt-7 grid gap-6 md:grid-cols-3">{[
      ["Plan a break around work or college", "Check the departure night, return time and door-to-door travel. For IT and other working professionals, a late Sunday return can matter as much as the number of days away. Confirm the schedule before arranging leave.", "/bengaluru/weekend-trips"],
      ["Pick your first trek", "Compare difficulty, distance, walking time and transport. Check the carry list and ask about guide arrangements, permits and weather changes before choosing a trail.", "/bengaluru/treks"],
      ["Plan for a family or friend group", "Agree on room sharing, budget, preferred pace and must-have inclusions. Share children's ages, dietary needs or accessibility requirements with the team so they can check suitability.", "/corporate-group-trips"],
    ].map(([title, body, href]) => <article key={title} className="rounded-2xl bg-white p-6"><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-cmt-neutral-600">{body}</p><Link href={href} className="mt-5 inline-block font-semibold underline underline-offset-4">Read planning advice</Link></article>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 py-12"><h2 className="font-display text-3xl font-semibold">Questions about travelling from Bengaluru</h2><div className="mt-6 divide-y divide-cmt-neutral-200">{BENGALURU_FAQS.map(faq => <details key={faq.question} className="py-5"><summary className="cursor-pointer font-semibold">{faq.question}</summary><p className="mt-3 leading-7 text-cmt-neutral-600">{faq.answer}</p></details>)}</div></section>
    <section className="bg-cmt-primary-100 px-5 py-12"><div className="mx-auto max-w-7xl"><h2 className="font-display text-3xl font-semibold">Thinking beyond the weekend?</h2><p className="mt-3 max-w-2xl leading-7">Explore holidays across India and abroad. Check where each itinerary starts and whether flights or transport from Bengaluru are included.</p><div className="mt-6 flex flex-wrap gap-5"><Link href="/packages?region=india" className="font-semibold underline">Domestic holidays</Link><Link href="/packages?region=international" className="font-semibold underline">International holidays</Link><Link href="/contact" className="font-semibold underline">Plan my trip</Link></div></div></section>
  </main><Footer /></>;
}
